from django.urls import path
import views

urlpatterns = [
    path("api/v1/health", views.health),
    path("api/v1/ready", views.ready),
    path("api/v1/auth/capabilities", views.auth_capabilities),
    path("api/v1/auth/signup", views.signup),
    path("api/v1/auth/signup/resend", views.signup_resend),
    path("api/v1/auth/signup/verify", views.signup_verify),
    path("api/v1/auth/password/login", views.password_login),
    path("api/v1/auth/otp/request", views.otp_request),
    path("api/v1/auth/otp/verify", views.otp_verify),
    path("api/v1/auth/token/refresh", views.token_refresh),
    path("api/v1/auth/logout", views.logout),
    path("api/v1/profile", views.profile),
    path("api/v1/profile/password/otp/request", views.profile_password_otp_request),
    path("api/v1/profile/password", views.profile_password_change),
    path("api/v1/profile/contact/request", views.profile_contact_request),
    path("api/v1/profile/contact/confirm", views.profile_contact_confirm),
    path("api/v1/cities", views.cities),
    path("api/v1/venues", views.venues),
    path("api/v1/sports", views.sports),
    path("api/v1/ticket-categories", views.ticket_categories),
    path("api/v1/payment-methods", views.payment_methods),
    path("api/v1/report-categories", views.report_categories),
    path("api/v1/amenities", views.amenities),
    path("api/v1/matches", views.matches),
    path("api/v1/tickets", views.tickets_search),
    path("api/v1/tickets/<int:ticket_id>", views.ticket_detail),
    path("api/v1/wallet", views.wallet),
    path("api/v1/wallet/top-up", views.wallet_top_up),
    path("api/v1/reservations", views.reservations),
    path("api/v1/reservations/<int:reservation_id>", views.reservation_detail),
    path("api/v1/reservations/<int:reservation_id>/pay", views.reservation_pay),
    path("api/v1/reservations/<int:reservation_id>/cancellation-quote", views.cancellation_quote),
    path("api/v1/reservations/<int:reservation_id>/cancellation-requests", views.cancellation_request),
    path("api/v1/reservations/<int:reservation_id>/seat-change-requests", views.seat_change_request),
    path("api/v1/seat-change-options", views.seat_change_options),
    path("api/v1/payments", views.payments),
    path("api/v1/bookings", views.bookings),
    path("api/v1/reports", views.reports),
    path("api/v1/issued-tickets", views.issued_tickets),
    path("api/v1/support-chat", views.support_chat),
    path("api/v1/support-chat/messages", views.support_chat_message),
    path("api/v1/support-chat/read", views.support_chat_read),
    path("api/v1/support/dashboard", views.support_dashboard),
    path("api/v1/support/reservations", views.support_reservations),
    path("api/v1/support/reservations/<int:reservation_id>/review", views.support_reservation_review),
    path("api/v1/support/reservations/<int:reservation_id>/seat-correction", views.support_reservation_seat_correction),
    path("api/v1/support/reservations/<int:reservation_id>/cancel", views.support_reservation_cancel),
    path("api/v1/support/payments/suspicious", views.support_suspicious_payments),
    path("api/v1/support/cancellation-requests", views.support_cancellation_requests),
    path("api/v1/support/cancellation-requests/<int:request_id_value>/review", views.support_cancellation_review),
    path("api/v1/support/seat-change-requests", views.support_seat_change_requests),
    path("api/v1/support/seat-change-requests/<int:request_id_value>/review", views.support_seat_change_review),
    path("api/v1/support/reports", views.support_reports),
    path("api/v1/support/reports/<int:report_id>", views.support_report_update),
    path("api/v1/support/chats", views.support_chats),
    path("api/v1/support/chats/<int:conversation_id>", views.support_chat_detail),
    path("api/v1/support/chats/<int:conversation_id>/messages", views.support_chat_reply),
    path("api/v1/support/chats/<int:conversation_id>/status", views.support_chat_status),
    path("api/v1/support/users/<int:user_id>/deactivate", views.support_user_deactivate),
    path("api/v1/support/tickets", views.support_tickets),
    path("api/v1/support/tickets/<int:ticket_id>", views.support_ticket_detail),
]

handler400 = "views.bad_request_handler"
handler403 = "views.permission_denied_handler"
handler404 = "views.not_found_handler"
handler500 = "views.server_error_handler"
