
BEGIN;

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

DROP VIEW IF EXISTS basketball_details CASCADE;
DROP VIEW IF EXISTS volleyball_details CASCADE;
DROP VIEW IF EXISTS football_details CASCADE;
DROP VIEW IF EXISTS v_purchased_tickets CASCADE;
DROP VIEW IF EXISTS v_ticket_catalog CASCADE;

DROP TABLE IF EXISTS support_messages CASCADE;
DROP TABLE IF EXISTS support_conversations CASCADE;
DROP TABLE IF EXISTS search_sync_outbox CASCADE;
DROP TABLE IF EXISTS api_audit_log CASCADE;
DROP TABLE IF EXISTS reservation_status_history CASCADE;
DROP TABLE IF EXISTS reports CASCADE;
DROP TABLE IF EXISTS report_categories CASCADE;
DROP TABLE IF EXISTS issued_tickets CASCADE;
DROP TABLE IF EXISTS seat_change_requests CASCADE;
DROP TABLE IF EXISTS refunds CASCADE;
DROP TABLE IF EXISTS cancellation_requests CASCADE;
DROP TABLE IF EXISTS cancellation_policies CASCADE;
DROP TABLE IF EXISTS wallet_transactions CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS payment_methods CASCADE;
DROP TABLE IF EXISTS reservations CASCADE;
DROP TABLE IF EXISTS ticket_amenities CASCADE;
DROP TABLE IF EXISTS amenities CASCADE;
DROP TABLE IF EXISTS tickets CASCADE;
DROP TABLE IF EXISTS ticket_categories CASCADE;
DROP TABLE IF EXISTS matches CASCADE;
DROP TABLE IF EXISTS organizers CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS sport_types CASCADE;
DROP TABLE IF EXISTS wallets CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS venues CASCADE;
DROP TABLE IF EXISTS cities CASCADE;
DROP TABLE IF EXISTS provinces CASCADE;

CREATE TABLE provinces (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_provinces_name UNIQUE (name),
    CONSTRAINT chk_provinces_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE cities (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    province_id  BIGINT NOT NULL REFERENCES provinces(id) ON DELETE RESTRICT,
    name         VARCHAR(100) NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_cities_province_name UNIQUE (province_id, name),
    CONSTRAINT chk_cities_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE venues (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id     BIGINT NOT NULL REFERENCES cities(id) ON DELETE RESTRICT,
    name        VARCHAR(200) NOT NULL,
    address     TEXT,
    capacity    INTEGER NOT NULL,
    latitude    NUMERIC(9,6),
    longitude   NUMERIC(9,6),
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_venues_city_name UNIQUE (city_id, name),
    CONSTRAINT chk_venues_capacity CHECK (capacity > 0),
    CONSTRAINT chk_venues_latitude CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT chk_venues_longitude CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    CONSTRAINT chk_venues_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id             BIGINT REFERENCES cities(id) ON DELETE SET NULL,
    first_name          VARCHAR(100) NOT NULL,
    last_name           VARCHAR(100) NOT NULL,
    email               CITEXT,
    phone               VARCHAR(20),
    password_hash       VARCHAR(255) NOT NULL,
    role                VARCHAR(20) NOT NULL DEFAULT 'spectator',
    date_of_birth       DATE,
    profile_picture_url TEXT,
    preferred_login     VARCHAR(10) NOT NULL DEFAULT 'email',
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_phone UNIQUE (phone),
    CONSTRAINT chk_users_role CHECK (role IN ('spectator', 'support')),
    CONSTRAINT chk_users_preferred_login CHECK (preferred_login IN ('email', 'phone')),
    CONSTRAINT chk_users_contact CHECK (email IS NOT NULL OR phone IS NOT NULL),
    CONSTRAINT chk_users_preferred_login_contact CHECK (
        (preferred_login = 'email' AND email IS NOT NULL)
        OR
        (preferred_login = 'phone' AND phone IS NOT NULL)
    ),
    CONSTRAINT chk_users_password_hash_not_blank CHECK (btrim(password_hash) <> ''),
    CONSTRAINT chk_users_email_format CHECK (
        email IS NULL OR email::TEXT ~* '^[A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,}$'
    ),
    CONSTRAINT chk_users_phone_format CHECK (
        phone IS NULL OR phone ~ '^\+?[0-9]{10,15}$'
    ),
    CONSTRAINT chk_users_names CHECK (btrim(first_name) <> '' AND btrim(last_name) <> ''),
    CONSTRAINT chk_users_birth_date_lower_bound CHECK (
        date_of_birth IS NULL OR date_of_birth >= DATE '1900-01-01'
    )
);

CREATE TABLE wallets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    balance     NUMERIC(14,2) NOT NULL DEFAULT 0,
    currency    CHAR(3) NOT NULL DEFAULT 'IRR',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_wallets_user UNIQUE (user_id),
    CONSTRAINT chk_wallets_balance CHECK (balance >= 0),
    CONSTRAINT chk_wallets_currency CHECK (currency ~ '^[A-Z]{3}$')
);

CREATE TABLE sport_types (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50) NOT NULL,
    name        VARCHAR(100) NOT NULL,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_sport_types_code UNIQUE (code),
    CONSTRAINT uq_sport_types_name UNIQUE (name),
    CONSTRAINT chk_sport_types_code CHECK (code ~ '^[a-z0-9_]+$'),
    CONSTRAINT chk_sport_types_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE teams (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_type_id  BIGINT NOT NULL REFERENCES sport_types(id) ON DELETE RESTRICT,
    city_id        BIGINT REFERENCES cities(id) ON DELETE SET NULL,
    name           VARCHAR(200) NOT NULL,
    short_name     VARCHAR(50),
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_teams_sport_name UNIQUE (sport_type_id, name),
    CONSTRAINT chk_teams_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE organizers (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(200) NOT NULL,
    support_email  CITEXT,
    support_phone  VARCHAR(20),
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_organizers_name UNIQUE (name),
    CONSTRAINT uq_organizers_email UNIQUE (support_email),
    CONSTRAINT uq_organizers_phone UNIQUE (support_phone),
    CONSTRAINT chk_organizers_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT chk_organizers_contact CHECK (support_email IS NOT NULL OR support_phone IS NOT NULL),
    CONSTRAINT chk_organizers_email_format CHECK (
        support_email IS NULL OR support_email::TEXT ~* '^[A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,}$'
    ),
    CONSTRAINT chk_organizers_phone_format CHECK (
        support_phone IS NULL OR support_phone ~ '^\+?[0-9]{10,15}$'
    )
);

CREATE TABLE matches (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_type_id  BIGINT NOT NULL REFERENCES sport_types(id) ON DELETE RESTRICT,
    home_team_id   BIGINT NOT NULL REFERENCES teams(id) ON DELETE RESTRICT,
    away_team_id   BIGINT NOT NULL REFERENCES teams(id) ON DELETE RESTRICT,
    venue_id       BIGINT NOT NULL REFERENCES venues(id) ON DELETE RESTRICT,
    organizer_id   BIGINT NOT NULL REFERENCES organizers(id) ON DELETE RESTRICT,
    tournament_name VARCHAR(200) NOT NULL,
    starts_at      TIMESTAMPTZ NOT NULL,
    ends_at        TIMESTAMPTZ,
    status         VARCHAR(20) NOT NULL DEFAULT 'scheduled',
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_matches_different_teams CHECK (home_team_id <> away_team_id),
    CONSTRAINT chk_matches_time CHECK (ends_at IS NULL OR ends_at > starts_at),
    CONSTRAINT chk_matches_status CHECK (status IN ('scheduled', 'postponed', 'canceled', 'completed')),
    CONSTRAINT chk_matches_tournament_not_blank CHECK (btrim(tournament_name) <> '')
);

CREATE TABLE ticket_categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50) NOT NULL,
    name        VARCHAR(100) NOT NULL,
    sort_order  SMALLINT NOT NULL DEFAULT 0,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_ticket_categories_code UNIQUE (code),
    CONSTRAINT uq_ticket_categories_name UNIQUE (name),
    CONSTRAINT chk_ticket_categories_code CHECK (code ~ '^[a-z0-9_]+$'),
    CONSTRAINT chk_ticket_categories_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE tickets (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id           BIGINT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    ticket_category_id BIGINT NOT NULL REFERENCES ticket_categories(id) ON DELETE RESTRICT,
    section_code       VARCHAR(50) NOT NULL,
    row_code           VARCHAR(50),
    seat_code          VARCHAR(50),
    is_numbered        BOOLEAN NOT NULL DEFAULT FALSE,
    price              NUMERIC(14,2) NOT NULL,
    total_capacity     INTEGER NOT NULL,
    held_quantity        INTEGER NOT NULL DEFAULT 0,
    sold_quantity        INTEGER NOT NULL DEFAULT 0,
    change_held_quantity INTEGER NOT NULL DEFAULT 0,
    available_quantity   INTEGER GENERATED ALWAYS AS
        (total_capacity - held_quantity - sold_quantity - change_held_quantity) STORED,
    sale_starts_at     TIMESTAMPTZ,
    sale_ends_at       TIMESTAMPTZ,
    is_active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_tickets_price CHECK (price >= 0),
    CONSTRAINT chk_tickets_capacity CHECK (total_capacity > 0),
    CONSTRAINT chk_tickets_quantities CHECK (
        held_quantity >= 0 AND sold_quantity >= 0 AND change_held_quantity >= 0 AND
        held_quantity + sold_quantity + change_held_quantity <= total_capacity
    ),
    CONSTRAINT chk_tickets_numbered_shape CHECK (
        (is_numbered = FALSE AND row_code IS NULL AND seat_code IS NULL)
        OR
        (is_numbered = TRUE AND row_code IS NOT NULL AND seat_code IS NOT NULL AND total_capacity = 1)
    ),
    CONSTRAINT chk_tickets_sale_window CHECK (
        sale_ends_at IS NULL OR sale_starts_at IS NULL OR sale_ends_at > sale_starts_at
    ),
    CONSTRAINT chk_tickets_section_not_blank CHECK (btrim(section_code) <> '')
);

CREATE TABLE amenities (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50) NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    CONSTRAINT uq_amenities_code UNIQUE (code),
    CONSTRAINT uq_amenities_name UNIQUE (name),
    CONSTRAINT chk_amenities_code CHECK (code ~ '^[a-z0-9_]+$'),
    CONSTRAINT chk_amenities_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE ticket_amenities (
    ticket_id   BIGINT NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
    amenity_id  BIGINT NOT NULL REFERENCES amenities(id) ON DELETE RESTRICT,
    details     VARCHAR(255),
    PRIMARY KEY (ticket_id, amenity_id)
);

CREATE TABLE reservations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    ticket_id           BIGINT NOT NULL REFERENCES tickets(id) ON DELETE RESTRICT,
    status              VARCHAR(20) NOT NULL DEFAULT 'held',
    quantity            INTEGER NOT NULL DEFAULT 1,
    unit_price          NUMERIC(14,2) NOT NULL,
    total_amount        NUMERIC(16,2) GENERATED ALWAYS AS (quantity * unit_price) STORED,
    reserved_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at          TIMESTAMPTZ NOT NULL,
    paid_at             TIMESTAMPTZ,
    canceled_at         TIMESTAMPTZ,
    canceled_by         BIGINT REFERENCES users(id) ON DELETE SET NULL,
    cancellation_reason TEXT,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_reservations_status CHECK (status IN ('held', 'paid', 'canceled', 'expired', 'refunded')),
    CONSTRAINT chk_reservations_quantity CHECK (quantity > 0),
    CONSTRAINT chk_reservations_unit_price CHECK (unit_price >= 0),
    CONSTRAINT chk_reservations_expiry CHECK (expires_at > reserved_at),
    CONSTRAINT chk_reservations_paid_at CHECK (paid_at IS NULL OR paid_at >= reserved_at),
    CONSTRAINT chk_reservations_canceled_at CHECK (canceled_at IS NULL OR canceled_at >= reserved_at),
    CONSTRAINT chk_reservations_lifecycle CHECK (
        (status = 'held'
            AND paid_at IS NULL AND canceled_at IS NULL AND canceled_by IS NULL
            AND cancellation_reason IS NULL)
        OR
        (status = 'paid'
            AND paid_at IS NOT NULL AND canceled_at IS NULL AND canceled_by IS NULL
            AND cancellation_reason IS NULL)
        OR
        (status = 'canceled'
            AND paid_at IS NULL AND canceled_at IS NOT NULL AND canceled_by IS NOT NULL
            AND cancellation_reason IS NOT NULL AND btrim(cancellation_reason) <> '')
        OR
        (status = 'expired'
            AND paid_at IS NULL AND canceled_at IS NOT NULL AND canceled_by IS NULL
            AND cancellation_reason IS NOT NULL AND btrim(cancellation_reason) <> '')
        OR
        (status = 'refunded'
            AND paid_at IS NOT NULL AND canceled_at IS NOT NULL AND canceled_at >= paid_at
            AND canceled_by IS NOT NULL
            AND cancellation_reason IS NOT NULL AND btrim(cancellation_reason) <> '')
    )
);

CREATE TABLE payment_methods (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50) NOT NULL,
    name        VARCHAR(100) NOT NULL,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_payment_methods_code UNIQUE (code),
    CONSTRAINT uq_payment_methods_name UNIQUE (name),
    CONSTRAINT chk_payment_methods_code CHECK (code ~ '^[a-z0-9_]+$')
);

CREATE TABLE payments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id    BIGINT NOT NULL REFERENCES reservations(id) ON DELETE RESTRICT,
    payment_method_id BIGINT NOT NULL REFERENCES payment_methods(id) ON DELETE RESTRICT,
    amount            NUMERIC(16,2) NOT NULL,
    status            VARCHAR(20) NOT NULL DEFAULT 'pending',
    transaction_ref   VARCHAR(100) NOT NULL,
    failure_reason    TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at           TIMESTAMPTZ,
    CONSTRAINT uq_payments_transaction_ref UNIQUE (transaction_ref),
    CONSTRAINT chk_payments_transaction_ref CHECK (btrim(transaction_ref) <> ''),
    CONSTRAINT chk_payments_amount CHECK (amount >= 0),
    CONSTRAINT chk_payments_status CHECK (status IN ('pending', 'successful', 'failed', 'canceled')),
    CONSTRAINT chk_payments_paid_at CHECK (
        (status = 'successful' AND paid_at IS NOT NULL)
        OR
        (status <> 'successful' AND paid_at IS NULL)
    ),
    CONSTRAINT chk_payments_failure_reason CHECK (
        (status = 'failed' AND failure_reason IS NOT NULL AND btrim(failure_reason) <> '')
        OR
        (status <> 'failed' AND failure_reason IS NULL)
    )
);

CREATE TABLE wallet_transactions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id       BIGINT NOT NULL REFERENCES wallets(id) ON DELETE RESTRICT,
    payment_id      BIGINT REFERENCES payments(id) ON DELETE RESTRICT,
    transaction_type VARCHAR(20) NOT NULL,
    amount          NUMERIC(16,2) NOT NULL,
    balance_after   NUMERIC(16,2) NOT NULL,
    reference_code  VARCHAR(100) NOT NULL,
    description     TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_wallet_transactions_reference UNIQUE (reference_code),
    CONSTRAINT chk_wallet_transactions_reference CHECK (btrim(reference_code) <> ''),
    CONSTRAINT chk_wallet_transactions_type CHECK (transaction_type IN ('top_up', 'purchase', 'refund', 'adjustment')),
    CONSTRAINT chk_wallet_transactions_amount CHECK (amount <> 0),
    CONSTRAINT chk_wallet_transactions_balance CHECK (balance_after >= 0)
);

CREATE TABLE cancellation_policies (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id          BIGINT NOT NULL REFERENCES organizers(id) ON DELETE CASCADE,
    hours_before_match    INTEGER NOT NULL,
    penalty_percentage    NUMERIC(5,2) NOT NULL,
    description           VARCHAR(255),
    CONSTRAINT uq_cancellation_policy UNIQUE (organizer_id, hours_before_match),
    CONSTRAINT chk_cancellation_policy_hours CHECK (hours_before_match >= 0),
    CONSTRAINT chk_cancellation_policy_penalty CHECK (penalty_percentage BETWEEN 0 AND 100)
);

CREATE TABLE cancellation_requests (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id         BIGINT NOT NULL REFERENCES reservations(id) ON DELETE RESTRICT,
    requested_by           BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    reason                 TEXT NOT NULL,
    status                 VARCHAR(20) NOT NULL DEFAULT 'pending',
    estimated_penalty_pct  NUMERIC(5,2),
    estimated_refund       NUMERIC(16,2),
    reviewed_by            BIGINT REFERENCES users(id) ON DELETE SET NULL,
    review_note            TEXT,
    requested_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at            TIMESTAMPTZ,
    CONSTRAINT chk_cancellation_requests_status CHECK (status IN ('pending', 'approved', 'rejected', 'processed')),
    CONSTRAINT chk_cancellation_requests_reason CHECK (btrim(reason) <> ''),
    CONSTRAINT chk_cancellation_requests_penalty CHECK (
        estimated_penalty_pct IS NULL OR estimated_penalty_pct BETWEEN 0 AND 100
    ),
    CONSTRAINT chk_cancellation_requests_refund CHECK (estimated_refund IS NULL OR estimated_refund >= 0),
    CONSTRAINT chk_cancellation_requests_review_lifecycle CHECK (
        (status = 'pending' AND reviewed_by IS NULL AND reviewed_at IS NULL)
        OR
        (status IN ('approved', 'rejected', 'processed')
            AND reviewed_by IS NOT NULL
            AND reviewed_at IS NOT NULL
            AND reviewed_at >= requested_at)
    )
);

CREATE TABLE refunds (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cancellation_request_id  BIGINT NOT NULL REFERENCES cancellation_requests(id) ON DELETE RESTRICT,
    payment_id               BIGINT NOT NULL REFERENCES payments(id) ON DELETE RESTRICT,
    wallet_id                BIGINT NOT NULL REFERENCES wallets(id) ON DELETE RESTRICT,
    amount                   NUMERIC(16,2) NOT NULL,
    penalty_amount           NUMERIC(16,2) NOT NULL DEFAULT 0,
    status                   VARCHAR(20) NOT NULL DEFAULT 'pending',
    transaction_ref          VARCHAR(100) NOT NULL,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at             TIMESTAMPTZ,
    CONSTRAINT uq_refunds_request UNIQUE (cancellation_request_id),
    CONSTRAINT uq_refunds_payment UNIQUE (payment_id),
    CONSTRAINT uq_refunds_transaction_ref UNIQUE (transaction_ref),
    CONSTRAINT chk_refunds_transaction_ref CHECK (btrim(transaction_ref) <> ''),
    CONSTRAINT chk_refunds_amount CHECK (amount >= 0),
    CONSTRAINT chk_refunds_penalty CHECK (penalty_amount >= 0),
    CONSTRAINT chk_refunds_status CHECK (status IN ('pending', 'completed', 'failed')),
    CONSTRAINT chk_refunds_completed_at CHECK (
        (status = 'completed' AND completed_at IS NOT NULL)
        OR
        (status <> 'completed' AND completed_at IS NULL)
    )
);

CREATE TABLE seat_change_requests (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id        BIGINT NOT NULL REFERENCES reservations(id) ON DELETE RESTRICT,
    requested_by          BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    old_ticket_id         BIGINT NOT NULL REFERENCES tickets(id) ON DELETE RESTRICT,
    requested_ticket_id   BIGINT NOT NULL REFERENCES tickets(id) ON DELETE RESTRICT,
    quantity              INTEGER NOT NULL,
    old_unit_price        NUMERIC(14,2) NOT NULL,
    new_unit_price        NUMERIC(14,2) NOT NULL,
    target_hold_expires_at TIMESTAMPTZ NOT NULL,
    status                VARCHAR(20) NOT NULL DEFAULT 'pending',
    reviewed_by           BIGINT REFERENCES users(id) ON DELETE SET NULL,
    review_note           TEXT,
    requested_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at           TIMESTAMPTZ,
    CONSTRAINT chk_seat_change_different_tickets CHECK (old_ticket_id <> requested_ticket_id),
    CONSTRAINT chk_seat_change_quantity CHECK (quantity > 0),
    CONSTRAINT chk_seat_change_prices CHECK (old_unit_price >= 0 AND new_unit_price >= 0),
    CONSTRAINT chk_seat_change_equal_price CHECK (old_unit_price = new_unit_price),
    CONSTRAINT chk_seat_change_hold_window CHECK (target_hold_expires_at > requested_at),
    CONSTRAINT chk_seat_change_status CHECK (status IN ('pending', 'rejected', 'processed', 'expired')),
    CONSTRAINT chk_seat_change_review_lifecycle CHECK (
        (status = 'pending' AND reviewed_by IS NULL AND reviewed_at IS NULL)
        OR
        (status IN ('rejected', 'processed')
            AND reviewed_by IS NOT NULL
            AND reviewed_at IS NOT NULL
            AND reviewed_at >= requested_at)
        OR
        (status = 'expired'
            AND reviewed_by IS NULL
            AND reviewed_at IS NOT NULL
            AND reviewed_at >= requested_at)
    )
);

CREATE TABLE issued_tickets (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id   BIGINT NOT NULL REFERENCES reservations(id) ON DELETE RESTRICT,
    ticket_number    UUID NOT NULL DEFAULT gen_random_uuid(),
    qr_token         UUID NOT NULL DEFAULT gen_random_uuid(),
    status           VARCHAR(20) NOT NULL DEFAULT 'active',
    issued_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at          TIMESTAMPTZ,
    CONSTRAINT uq_issued_tickets_number UNIQUE (ticket_number),
    CONSTRAINT uq_issued_tickets_qr UNIQUE (qr_token),
    CONSTRAINT chk_issued_tickets_status CHECK (status IN ('active', 'used', 'canceled')),
    CONSTRAINT chk_issued_tickets_used_at CHECK (
        (status = 'used' AND used_at IS NOT NULL)
        OR
        (status <> 'used' AND used_at IS NULL)
    )
);

CREATE TABLE report_categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50) NOT NULL,
    name        VARCHAR(150) NOT NULL,
    CONSTRAINT uq_report_categories_code UNIQUE (code),
    CONSTRAINT uq_report_categories_name UNIQUE (name),
    CONSTRAINT chk_report_categories_code CHECK (code ~ '^[a-z0-9_]+$'),
    CONSTRAINT chk_report_categories_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE reports (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    ticket_id       BIGINT REFERENCES tickets(id) ON DELETE SET NULL,
    reservation_id  BIGINT REFERENCES reservations(id) ON DELETE SET NULL,
    payment_id      BIGINT REFERENCES payments(id) ON DELETE RESTRICT,
    category_id     BIGINT NOT NULL REFERENCES report_categories(id) ON DELETE RESTRICT,
    subject         VARCHAR(200) NOT NULL,
    description     TEXT NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'pending',
    assigned_to     BIGINT REFERENCES users(id) ON DELETE SET NULL,
    support_response TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at     TIMESTAMPTZ,
    CONSTRAINT chk_reports_target CHECK (
        ticket_id IS NOT NULL OR reservation_id IS NOT NULL OR payment_id IS NOT NULL
    ),
    CONSTRAINT chk_reports_status CHECK (status IN ('pending', 'in_review', 'resolved', 'rejected')),
    CONSTRAINT chk_reports_subject CHECK (btrim(subject) <> ''),
    CONSTRAINT chk_reports_description CHECK (btrim(description) <> ''),
    CONSTRAINT chk_reports_resolved_at CHECK (
        (status IN ('resolved', 'rejected') AND resolved_at IS NOT NULL)
        OR
        (status NOT IN ('resolved', 'rejected') AND resolved_at IS NULL)
    ),
    CONSTRAINT chk_reports_assignment_lifecycle CHECK (
        status = 'pending'
        OR (status IN ('in_review', 'resolved', 'rejected') AND assigned_to IS NOT NULL)
    ),
    CONSTRAINT chk_reports_resolution_time CHECK (
        resolved_at IS NULL OR resolved_at >= created_at
    )
);

CREATE TABLE reservation_status_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id  BIGINT NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
    old_status      VARCHAR(20),
    new_status      VARCHAR(20) NOT NULL,
    changed_by      BIGINT REFERENCES users(id) ON DELETE SET NULL,
    note            TEXT,
    changed_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_reservation_history_old_status CHECK (
        old_status IS NULL OR old_status IN ('held', 'paid', 'canceled', 'expired', 'refunded')
    ),
    CONSTRAINT chk_reservation_history_new_status CHECK (
        new_status IN ('held', 'paid', 'canceled', 'expired', 'refunded')
    )
);

CREATE OR REPLACE FUNCTION trg_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER set_updated_at_venues
BEFORE UPDATE ON venues
FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

CREATE TRIGGER set_updated_at_users
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

CREATE TRIGGER set_updated_at_wallets
BEFORE UPDATE ON wallets
FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

CREATE TRIGGER set_updated_at_organizers
BEFORE UPDATE ON organizers
FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

CREATE TRIGGER set_updated_at_matches
BEFORE UPDATE ON matches
FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

CREATE TRIGGER set_updated_at_tickets
BEFORE UPDATE ON tickets
FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

CREATE TRIGGER set_updated_at_reservations
BEFORE UPDATE ON reservations
FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

CREATE TRIGGER set_updated_at_reports
BEFORE UPDATE ON reports
FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

CREATE OR REPLACE FUNCTION trg_create_user_wallet()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO wallets(user_id, balance, currency)
    VALUES (NEW.id, 0, 'IRR')
    ON CONFLICT (user_id) DO NOTHING;
    RETURN NEW;
END;
$$;

CREATE TRIGGER create_user_wallet
AFTER INSERT ON users
FOR EACH ROW EXECUTE FUNCTION trg_create_user_wallet();

CREATE OR REPLACE FUNCTION trg_validate_user_birth_date()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.date_of_birth IS NOT NULL AND NEW.date_of_birth >= CURRENT_DATE THEN
        RAISE EXCEPTION 'Date of birth must be earlier than today.';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER validate_user_birth_date
BEFORE INSERT OR UPDATE OF date_of_birth ON users
FOR EACH ROW EXECUTE FUNCTION trg_validate_user_birth_date();

CREATE OR REPLACE FUNCTION trg_validate_match_teams()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_home_sport BIGINT;
    v_away_sport BIGINT;
BEGIN
    SELECT sport_type_id INTO v_home_sport
    FROM teams WHERE id = NEW.home_team_id FOR KEY SHARE;

    SELECT sport_type_id INTO v_away_sport
    FROM teams WHERE id = NEW.away_team_id FOR KEY SHARE;

    IF v_home_sport IS DISTINCT FROM NEW.sport_type_id
       OR v_away_sport IS DISTINCT FROM NEW.sport_type_id THEN
        RAISE EXCEPTION 'Both teams must belong to match sport_type_id %.', NEW.sport_type_id;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER validate_match_teams
BEFORE INSERT OR UPDATE OF sport_type_id, home_team_id, away_team_id ON matches
FOR EACH ROW EXECUTE FUNCTION trg_validate_match_teams();

CREATE OR REPLACE FUNCTION trg_validate_team_sport_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.sport_type_id IS DISTINCT FROM OLD.sport_type_id
       AND EXISTS (
            SELECT 1 FROM matches m
            WHERE (m.home_team_id = OLD.id OR m.away_team_id = OLD.id)
              AND m.sport_type_id <> NEW.sport_type_id
       ) THEN
        RAISE EXCEPTION 'Team % is already used by matches of another sport type.', OLD.id;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER validate_team_sport_change
BEFORE UPDATE OF sport_type_id ON teams
FOR EACH ROW EXECUTE FUNCTION trg_validate_team_sport_change();

CREATE OR REPLACE FUNCTION trg_validate_ticket_capacity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_venue_capacity INTEGER;
    v_match_starts   TIMESTAMPTZ;
    v_allocated      BIGINT;
BEGIN
    SELECT v.capacity, m.starts_at
    INTO v_venue_capacity, v_match_starts
    FROM matches m
    JOIN venues v ON v.id = m.venue_id
    WHERE m.id = NEW.match_id
    FOR UPDATE OF m;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Match % does not exist.', NEW.match_id;
    END IF;

    SELECT COALESCE(SUM(total_capacity), 0)
    INTO v_allocated
    FROM tickets
    WHERE match_id = NEW.match_id
      AND id <> COALESCE(NEW.id, -1);

    IF v_allocated + NEW.total_capacity > v_venue_capacity THEN
        RAISE EXCEPTION 'Allocated ticket capacity (%) exceeds venue capacity (%).',
            v_allocated + NEW.total_capacity, v_venue_capacity;
    END IF;

    IF NEW.sale_starts_at IS NOT NULL AND NEW.sale_starts_at >= v_match_starts THEN
        RAISE EXCEPTION 'Ticket sale must start before the match begins.';
    END IF;
    IF NEW.sale_ends_at IS NOT NULL AND NEW.sale_ends_at > v_match_starts THEN
        RAISE EXCEPTION 'Ticket sale cannot end after the match begins.';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER validate_ticket_capacity
BEFORE INSERT OR UPDATE OF match_id, total_capacity, sale_starts_at, sale_ends_at ON tickets
FOR EACH ROW EXECUTE FUNCTION trg_validate_ticket_capacity();

CREATE OR REPLACE FUNCTION trg_validate_match_venue_capacity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_venue_capacity INTEGER;
    v_allocated BIGINT;
BEGIN
    SELECT capacity INTO v_venue_capacity FROM venues WHERE id = NEW.venue_id;
    SELECT COALESCE(SUM(total_capacity),0) INTO v_allocated FROM tickets WHERE match_id = NEW.id;
    IF v_allocated > v_venue_capacity THEN
        RAISE EXCEPTION 'Match % has % allocated tickets, exceeding new venue capacity %.',
            NEW.id, v_allocated, v_venue_capacity;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER validate_match_venue_capacity
BEFORE UPDATE OF venue_id ON matches
FOR EACH ROW EXECUTE FUNCTION trg_validate_match_venue_capacity();

CREATE OR REPLACE FUNCTION trg_validate_venue_capacity_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE rec RECORD;
BEGIN
    IF NEW.capacity < OLD.capacity THEN
        PERFORM 1 FROM matches WHERE venue_id = OLD.id ORDER BY id FOR UPDATE;
        FOR rec IN
            SELECT m.id, COALESCE(SUM(t.total_capacity),0) AS allocated
            FROM matches m LEFT JOIN tickets t ON t.match_id=m.id
            WHERE m.venue_id=OLD.id GROUP BY m.id
        LOOP
            IF rec.allocated > NEW.capacity THEN
                RAISE EXCEPTION 'Venue capacity % is below the % tickets allocated for match %.',
                    NEW.capacity, rec.allocated, rec.id;
            END IF;
        END LOOP;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER validate_venue_capacity_change
BEFORE UPDATE OF capacity ON venues
FOR EACH ROW EXECUTE FUNCTION trg_validate_venue_capacity_change();

CREATE OR REPLACE FUNCTION trg_validate_match_time_against_sales()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM tickets t
        WHERE t.match_id=NEW.id
          AND ((t.sale_starts_at IS NOT NULL AND t.sale_starts_at >= NEW.starts_at)
            OR (t.sale_ends_at IS NOT NULL AND t.sale_ends_at > NEW.starts_at))
    ) THEN
        RAISE EXCEPTION 'Match start time % conflicts with one or more ticket sale windows.', NEW.starts_at;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER validate_match_time_against_sales
BEFORE UPDATE OF starts_at ON matches
FOR EACH ROW EXECUTE FUNCTION trg_validate_match_time_against_sales();

CREATE OR REPLACE FUNCTION trg_validate_reservation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_ticket RECORD;
    v_user_role VARCHAR(20);
    v_user_active BOOLEAN;
BEGIN
    SELECT
        t.is_numbered,t.price,t.is_active AS ticket_active,
        t.sale_starts_at,t.sale_ends_at,
        m.status AS match_status,m.is_active AS match_active,m.starts_at,
        v.is_active AS venue_active,o.is_active AS organizer_active,
        st.is_active AS sport_active,ht.is_active AS home_team_active,
        at.is_active AS away_team_active,tc.is_active AS category_active
    INTO v_ticket
    FROM tickets t
    JOIN matches m ON m.id=t.match_id
    JOIN sport_types st ON st.id=m.sport_type_id
    JOIN teams ht ON ht.id=m.home_team_id
    JOIN teams at ON at.id=m.away_team_id
    JOIN venues v ON v.id=m.venue_id
    JOIN organizers o ON o.id=m.organizer_id
    JOIN ticket_categories tc ON tc.id=t.ticket_category_id
    WHERE t.id=NEW.ticket_id
    FOR SHARE OF t,m;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Ticket % does not exist.', NEW.ticket_id;
    END IF;
    IF v_ticket.is_numbered AND NEW.quantity <> 1 THEN
        RAISE EXCEPTION 'Numbered-seat tickets can only be reserved with quantity = 1.';
    END IF;
    IF NEW.unit_price <> v_ticket.price THEN
        RAISE EXCEPTION 'Reservation unit price % must equal current ticket price %.',
            NEW.unit_price, v_ticket.price;
    END IF;

    SELECT role,is_active
    INTO v_user_role,v_user_active
    FROM users
    WHERE id=NEW.user_id
    FOR SHARE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'User % does not exist.', NEW.user_id;
    END IF;
    IF v_user_role IS DISTINCT FROM 'spectator' THEN
        RAISE EXCEPTION 'Only spectator users may own reservations.';
    END IF;

    IF TG_OP='INSERT' THEN
        IF NOT v_user_active THEN
            RAISE EXCEPTION 'Inactive users cannot create reservations.';
        END IF;
    ELSIF NEW.user_id IS DISTINCT FROM OLD.user_id AND NOT v_user_active THEN
        RAISE EXCEPTION 'A reservation cannot be transferred to an inactive user.';
    END IF;

    IF TG_OP='INSERT' AND NEW.status='held' THEN
        IF NOT v_ticket.ticket_active OR NOT v_ticket.match_active
           OR NOT v_ticket.venue_active OR NOT v_ticket.organizer_active
           OR NOT v_ticket.sport_active OR NOT v_ticket.home_team_active
           OR NOT v_ticket.away_team_active OR NOT v_ticket.category_active
           OR v_ticket.match_status NOT IN ('scheduled','postponed')
           OR v_ticket.starts_at<=CURRENT_TIMESTAMP
           OR (v_ticket.sale_starts_at IS NOT NULL
               AND CURRENT_TIMESTAMP<v_ticket.sale_starts_at)
           OR (v_ticket.sale_ends_at IS NOT NULL
               AND CURRENT_TIMESTAMP>=v_ticket.sale_ends_at) THEN
            RAISE EXCEPTION 'A new hold must reference an active future sellable event.';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER validate_reservation
BEFORE INSERT OR UPDATE OF user_id, ticket_id, quantity, unit_price ON reservations
FOR EACH ROW EXECUTE FUNCTION trg_validate_reservation();

CREATE OR REPLACE FUNCTION trg_validate_support_user()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE v_user_id BIGINT; v_role VARCHAR(20);
BEGIN
    IF TG_TABLE_NAME='reports' THEN v_user_id:=NEW.assigned_to;
    ELSIF TG_TABLE_NAME='cancellation_requests' THEN v_user_id:=NEW.reviewed_by;
    ELSIF TG_TABLE_NAME='seat_change_requests' THEN v_user_id:=NEW.reviewed_by;
    ELSIF TG_TABLE_NAME='reservations' THEN v_user_id:=NEW.canceled_by;
    ELSE RETURN NEW; END IF;
    IF v_user_id IS NOT NULL THEN
        SELECT role INTO v_role FROM users WHERE id=v_user_id FOR SHARE;
        IF v_role IS DISTINCT FROM 'support' THEN
            RAISE EXCEPTION 'User % must have support role.', v_user_id;
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER validate_report_support BEFORE INSERT OR UPDATE OF assigned_to ON reports
FOR EACH ROW EXECUTE FUNCTION trg_validate_support_user();
CREATE TRIGGER validate_cancellation_support BEFORE INSERT OR UPDATE OF reviewed_by ON cancellation_requests
FOR EACH ROW EXECUTE FUNCTION trg_validate_support_user();
CREATE TRIGGER validate_seat_change_support BEFORE INSERT OR UPDATE OF reviewed_by ON seat_change_requests
FOR EACH ROW EXECUTE FUNCTION trg_validate_support_user();
CREATE TRIGGER validate_reservation_canceler BEFORE INSERT OR UPDATE OF canceled_by ON reservations
FOR EACH ROW EXECUTE FUNCTION trg_validate_support_user();

CREATE OR REPLACE FUNCTION trg_protect_support_role_change()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF OLD.role='support' AND NEW.role<>'support' AND (
        EXISTS(SELECT 1 FROM reservations WHERE canceled_by=OLD.id)
        OR EXISTS(SELECT 1 FROM cancellation_requests WHERE reviewed_by=OLD.id)
        OR EXISTS(SELECT 1 FROM seat_change_requests WHERE reviewed_by=OLD.id)
        OR EXISTS(SELECT 1 FROM reports WHERE assigned_to=OLD.id)
    ) THEN RAISE EXCEPTION 'User % is referenced as a support actor and cannot lose support role.', OLD.id;
    END IF;
    RETURN NEW;
END; $$;
CREATE TRIGGER protect_support_role_change BEFORE UPDATE OF role ON users
FOR EACH ROW EXECUTE FUNCTION trg_protect_support_role_change();

CREATE OR REPLACE FUNCTION trg_validate_payment_amount()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE v_total NUMERIC(16,2);
BEGIN
    SELECT total_amount INTO v_total FROM reservations WHERE id=NEW.reservation_id;
    IF NEW.amount <> v_total THEN
        RAISE EXCEPTION 'Payment amount % must equal reservation total %.', NEW.amount,v_total;
    END IF;
    RETURN NEW;
END; $$;
CREATE TRIGGER validate_payment_amount BEFORE INSERT OR UPDATE OF reservation_id,amount ON payments
FOR EACH ROW EXECUTE FUNCTION trg_validate_payment_amount();

CREATE OR REPLACE FUNCTION trg_validate_cancellation_request_links()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE v_owner BIGINT;
BEGIN
    SELECT user_id INTO v_owner FROM reservations WHERE id=NEW.reservation_id;
    IF NEW.requested_by <> v_owner THEN
        RAISE EXCEPTION 'Cancellation requester must own the reservation.';
    END IF;
    RETURN NEW;
END; $$;
CREATE TRIGGER validate_cancellation_request_links
BEFORE INSERT OR UPDATE OF reservation_id,requested_by ON cancellation_requests
FOR EACH ROW EXECUTE FUNCTION trg_validate_cancellation_request_links();

CREATE OR REPLACE FUNCTION trg_validate_refund_links()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    v_req_res BIGINT; v_pay_res BIGINT; v_pay_amt NUMERIC(16,2); v_pay_status VARCHAR(20);
    v_res_user BIGINT; v_wallet_user BIGINT;
BEGIN
    SELECT reservation_id INTO v_req_res FROM cancellation_requests WHERE id=NEW.cancellation_request_id;
    SELECT reservation_id,amount,status INTO v_pay_res,v_pay_amt,v_pay_status FROM payments WHERE id=NEW.payment_id;
    SELECT user_id INTO v_res_user FROM reservations WHERE id=v_req_res;
    SELECT user_id INTO v_wallet_user FROM wallets WHERE id=NEW.wallet_id;
    IF v_req_res IS DISTINCT FROM v_pay_res THEN RAISE EXCEPTION 'Refund request and payment must reference same reservation.'; END IF;
    IF v_pay_status IS DISTINCT FROM 'successful' THEN RAISE EXCEPTION 'Refund must reference successful payment.'; END IF;
    IF v_wallet_user IS DISTINCT FROM v_res_user THEN RAISE EXCEPTION 'Refund wallet must belong to reservation owner.'; END IF;
    IF NEW.amount + NEW.penalty_amount <> v_pay_amt THEN
        RAISE EXCEPTION 'Refund amount plus penalty must equal payment amount %.', v_pay_amt;
    END IF;
    RETURN NEW;
END; $$;
CREATE TRIGGER validate_refund_links
BEFORE INSERT OR UPDATE OF cancellation_request_id,payment_id,wallet_id,amount,penalty_amount ON refunds
FOR EACH ROW EXECUTE FUNCTION trg_validate_refund_links();

CREATE OR REPLACE FUNCTION trg_validate_wallet_transaction_links()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_wallet_user    BIGINT;
    v_payment_user   BIGINT;
    v_status         VARCHAR(20);
    v_amount         NUMERIC(16,2);
    v_wallet_balance NUMERIC(16,2);
    v_ledger_before  NUMERIC(16,2);
    v_latest_entry   TIMESTAMPTZ;
BEGIN
    IF NEW.transaction_type IN ('purchase','refund') AND NEW.payment_id IS NULL THEN
        RAISE EXCEPTION '% wallet transactions must reference a payment.', NEW.transaction_type;
    ELSIF NEW.transaction_type IN ('top_up','adjustment') AND NEW.payment_id IS NOT NULL THEN
        RAISE EXCEPTION '% transaction cannot reference a payment.', NEW.transaction_type;
    END IF;

    SELECT user_id,balance
    INTO v_wallet_user,v_wallet_balance
    FROM wallets
    WHERE id=NEW.wallet_id
    FOR KEY SHARE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Wallet % does not exist.', NEW.wallet_id;
    END IF;

    SELECT COALESCE(SUM(amount),0),MAX(created_at)
    INTO v_ledger_before,v_latest_entry
    FROM wallet_transactions
    WHERE wallet_id=NEW.wallet_id;

    IF v_latest_entry IS NOT NULL AND NEW.created_at<v_latest_entry THEN
        RAISE EXCEPTION 'Wallet ledger entries must be appended chronologically.';
    END IF;

    IF NEW.balance_after <> v_wallet_balance
       OR NEW.balance_after <> v_ledger_before + NEW.amount THEN
        RAISE EXCEPTION 'Wallet ledger mismatch for wallet %: current balance %, previous ledger %, amount %, balance_after %.',
            NEW.wallet_id,v_wallet_balance,v_ledger_before,NEW.amount,NEW.balance_after;
    END IF;

    IF NEW.payment_id IS NOT NULL THEN
        SELECT r.user_id,p.status,p.amount
        INTO v_payment_user,v_status,v_amount
        FROM payments p
        JOIN reservations r ON r.id=p.reservation_id
        WHERE p.id=NEW.payment_id;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Payment % does not exist.', NEW.payment_id;
        END IF;
        IF v_wallet_user IS DISTINCT FROM v_payment_user THEN
            RAISE EXCEPTION 'Payment must belong to wallet owner.';
        END IF;
        IF v_status IS DISTINCT FROM 'successful' THEN
            RAISE EXCEPTION '% wallet transaction must reference a successful payment.',NEW.transaction_type;
        END IF;
        IF NEW.transaction_type='purchase' AND NEW.amount <> -v_amount THEN
            RAISE EXCEPTION 'Wallet purchase amount must equal negative payment amount.';
        END IF;
        IF NEW.transaction_type='refund' AND NOT EXISTS(
            SELECT 1
            FROM refunds rf
            WHERE rf.payment_id=NEW.payment_id
              AND rf.wallet_id=NEW.wallet_id
              AND rf.status='completed'
              AND rf.amount=NEW.amount
        ) THEN
            RAISE EXCEPTION 'Wallet refund must match a completed refund record.';
        END IF;
    END IF;

    IF NEW.transaction_type='purchase' AND NEW.amount>=0 THEN
        RAISE EXCEPTION 'Purchase amount must be negative.';
    ELSIF NEW.transaction_type IN ('top_up','refund') AND NEW.amount<=0 THEN
        RAISE EXCEPTION '% amount must be positive.',NEW.transaction_type;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER validate_wallet_transaction_links
BEFORE INSERT ON wallet_transactions
FOR EACH ROW EXECUTE FUNCTION trg_validate_wallet_transaction_links();

CREATE OR REPLACE FUNCTION trg_protect_wallet_transaction_immutability()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'wallet_transactions is append-only; insert an adjustment row instead.';
END;
$$;

CREATE TRIGGER protect_wallet_transaction_immutability
BEFORE UPDATE OR DELETE ON wallet_transactions
FOR EACH ROW EXECUTE FUNCTION trg_protect_wallet_transaction_immutability();

CREATE UNIQUE INDEX uq_wallet_purchase_per_payment
    ON wallet_transactions(payment_id) WHERE transaction_type='purchase';
CREATE UNIQUE INDEX uq_wallet_refund_per_payment
    ON wallet_transactions(payment_id) WHERE transaction_type='refund';

CREATE OR REPLACE FUNCTION trg_validate_seat_change_request_links()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_owner   BIGINT;
    v_current BIGINT;
    v_qty     INTEGER;
    v_price   NUMERIC(14,2);
    v_old     RECORD;
    v_new     RECORD;
    v_definition_changed BOOLEAN;
BEGIN
    SELECT user_id,ticket_id,quantity,unit_price
    INTO v_owner,v_current,v_qty,v_price
    FROM reservations
    WHERE id=NEW.reservation_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Reservation % does not exist.', NEW.reservation_id;
    END IF;
    IF NEW.requested_by<>v_owner THEN
        RAISE EXCEPTION 'Seat-change requester must own reservation.';
    END IF;

    SELECT match_id,price,is_numbered,total_capacity
    INTO v_old
    FROM tickets WHERE id=NEW.old_ticket_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Old ticket % does not exist.', NEW.old_ticket_id;
    END IF;

    SELECT match_id,price,is_numbered,total_capacity
    INTO v_new
    FROM tickets WHERE id=NEW.requested_ticket_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Requested ticket % does not exist.', NEW.requested_ticket_id;
    END IF;

    v_definition_changed := TG_OP='INSERT';
    IF TG_OP='UPDATE' THEN
        v_definition_changed :=
            NEW.reservation_id IS DISTINCT FROM OLD.reservation_id OR
            NEW.requested_by IS DISTINCT FROM OLD.requested_by OR
            NEW.old_ticket_id IS DISTINCT FROM OLD.old_ticket_id OR
            NEW.requested_ticket_id IS DISTINCT FROM OLD.requested_ticket_id OR
            NEW.quantity IS DISTINCT FROM OLD.quantity OR
            NEW.old_unit_price IS DISTINCT FROM OLD.old_unit_price OR
            NEW.new_unit_price IS DISTINCT FROM OLD.new_unit_price;
    END IF;

    IF v_definition_changed THEN
        IF NEW.quantity<>v_qty THEN
            RAISE EXCEPTION 'Seat-change quantity must equal reservation quantity %.',v_qty;
        END IF;
        IF v_old.match_id<>v_new.match_id THEN
            RAISE EXCEPTION 'Seat/section changes must stay within the same match.';
        END IF;
        IF NEW.old_unit_price<>v_price
           OR NEW.new_unit_price<>v_new.price
           OR NEW.old_unit_price<>NEW.new_unit_price THEN
            RAISE EXCEPTION 'Seat/section changes require a same-price reservation snapshot.';
        END IF;
        IF v_new.is_numbered AND NEW.quantity<>1 THEN
            RAISE EXCEPTION 'A numbered destination seat requires quantity 1.';
        END IF;
    END IF;

    IF NEW.status='processed' AND v_current<>NEW.requested_ticket_id THEN
        RAISE EXCEPTION 'Processed seat change must point to reservation current ticket.';
    ELSIF NEW.status<>'processed' AND v_current<>NEW.old_ticket_id THEN
        RAISE EXCEPTION 'Unprocessed seat change must retain old ticket.';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER validate_seat_change_request_links
BEFORE INSERT OR UPDATE OF reservation_id,requested_by,old_ticket_id,requested_ticket_id,
    quantity,old_unit_price,new_unit_price,status ON seat_change_requests
FOR EACH ROW EXECUTE FUNCTION trg_validate_seat_change_request_links();

CREATE OR REPLACE FUNCTION trg_validate_report_links()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE v_ru BIGINT; v_rt BIGINT; v_pr BIGINT;
BEGIN
    IF NEW.reservation_id IS NOT NULL THEN
        SELECT user_id,ticket_id INTO v_ru,v_rt FROM reservations WHERE id=NEW.reservation_id;
        IF NEW.reporter_id<>v_ru THEN RAISE EXCEPTION 'Reporter must own reservation.'; END IF;
        IF NEW.ticket_id IS NOT NULL AND NEW.ticket_id<>v_rt THEN RAISE EXCEPTION 'Report ticket does not match reservation.'; END IF;
    END IF;
    IF NEW.payment_id IS NOT NULL THEN
        SELECT reservation_id INTO v_pr FROM payments WHERE id=NEW.payment_id;
        IF NEW.reservation_id IS NOT NULL AND NEW.reservation_id<>v_pr THEN RAISE EXCEPTION 'Report payment does not match reservation.'; END IF;
        IF NEW.reservation_id IS NULL THEN
            SELECT user_id,ticket_id INTO v_ru,v_rt FROM reservations WHERE id=v_pr;
            IF NEW.reporter_id<>v_ru THEN RAISE EXCEPTION 'Reporter must own payment.'; END IF;
            IF NEW.ticket_id IS NOT NULL AND NEW.ticket_id<>v_rt THEN RAISE EXCEPTION 'Report ticket does not match payment.'; END IF;
        END IF;
    END IF;
    RETURN NEW;
END; $$;
CREATE TRIGGER validate_report_links
BEFORE INSERT OR UPDATE OF reporter_id,ticket_id,reservation_id,payment_id ON reports
FOR EACH ROW EXECUTE FUNCTION trg_validate_report_links();

CREATE OR REPLACE FUNCTION trg_validate_status_transition()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE v_allowed BOOLEAN:=FALSE;
BEGIN
    IF NEW.status IS NOT DISTINCT FROM OLD.status THEN RETURN NEW; END IF;
    CASE TG_TABLE_NAME
      WHEN 'reservations' THEN v_allowed := (OLD.status='held' AND NEW.status IN ('paid','canceled','expired')) OR (OLD.status='paid' AND NEW.status='refunded');
      WHEN 'payments' THEN v_allowed := OLD.status='pending' AND NEW.status IN ('successful','failed','canceled');
      WHEN 'cancellation_requests' THEN v_allowed := (OLD.status='pending' AND NEW.status IN ('approved','rejected','processed')) OR (OLD.status='approved' AND NEW.status IN ('rejected','processed'));
      WHEN 'refunds' THEN v_allowed := OLD.status='pending' AND NEW.status IN ('completed','failed');
      WHEN 'seat_change_requests' THEN v_allowed := OLD.status='pending' AND NEW.status IN ('rejected','processed','expired');
      WHEN 'issued_tickets' THEN v_allowed := OLD.status='active' AND NEW.status IN ('used','canceled');
      WHEN 'reports' THEN v_allowed := (OLD.status='pending' AND NEW.status IN ('in_review','resolved','rejected')) OR (OLD.status='in_review' AND NEW.status IN ('resolved','rejected'));
      ELSE RETURN NEW;
    END CASE;
    IF NOT v_allowed THEN RAISE EXCEPTION 'Illegal status transition on %: % -> %.',TG_TABLE_NAME,OLD.status,NEW.status; END IF;
    RETURN NEW;
END; $$;
CREATE TRIGGER validate_reservation_status_transition BEFORE UPDATE OF status ON reservations FOR EACH ROW EXECUTE FUNCTION trg_validate_status_transition();
CREATE TRIGGER validate_payment_status_transition BEFORE UPDATE OF status ON payments FOR EACH ROW EXECUTE FUNCTION trg_validate_status_transition();
CREATE TRIGGER validate_cancellation_status_transition BEFORE UPDATE OF status ON cancellation_requests FOR EACH ROW EXECUTE FUNCTION trg_validate_status_transition();
CREATE TRIGGER validate_refund_status_transition BEFORE UPDATE OF status ON refunds FOR EACH ROW EXECUTE FUNCTION trg_validate_status_transition();
CREATE TRIGGER validate_seat_change_status_transition BEFORE UPDATE OF status ON seat_change_requests FOR EACH ROW EXECUTE FUNCTION trg_validate_status_transition();
CREATE TRIGGER validate_issued_ticket_status_transition BEFORE UPDATE OF status ON issued_tickets FOR EACH ROW EXECUTE FUNCTION trg_validate_status_transition();
CREATE TRIGGER validate_report_status_transition BEFORE UPDATE OF status ON reports FOR EACH ROW EXECUTE FUNCTION trg_validate_status_transition();

CREATE OR REPLACE FUNCTION trg_record_reservation_status()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP='INSERT' THEN
        INSERT INTO reservation_status_history(reservation_id,old_status,new_status,changed_by,note)
        VALUES(NEW.id,NULL,NEW.status,NEW.canceled_by,'Reservation created');
    ELSIF NEW.status IS DISTINCT FROM OLD.status THEN
        INSERT INTO reservation_status_history(reservation_id,old_status,new_status,changed_by,note)
        VALUES(NEW.id,OLD.status,NEW.status,NEW.canceled_by,NEW.cancellation_reason);
    END IF;
    RETURN NEW;
END; $$;
CREATE TRIGGER record_reservation_status AFTER INSERT OR UPDATE OF status ON reservations
FOR EACH ROW EXECUTE FUNCTION trg_record_reservation_status();

CREATE OR REPLACE FUNCTION trg_assert_ticket_inventory_counters()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_ids BIGINT[];
    v_id BIGINT;
    v_actual_held BIGINT;
    v_actual_sold BIGINT;
    v_actual_change_held BIGINT;
    v_stored RECORD;
BEGIN
    IF TG_TABLE_NAME='tickets' THEN
        IF TG_OP='INSERT' THEN v_ids:=ARRAY[NEW.id];
        ELSIF TG_OP='DELETE' THEN v_ids:=ARRAY[OLD.id];
        ELSE v_ids:=ARRAY[OLD.id,NEW.id]; END IF;
    ELSIF TG_TABLE_NAME='reservations' THEN
        IF TG_OP='INSERT' THEN v_ids:=ARRAY[NEW.ticket_id];
        ELSIF TG_OP='DELETE' THEN v_ids:=ARRAY[OLD.ticket_id];
        ELSE v_ids:=ARRAY[OLD.ticket_id,NEW.ticket_id]; END IF;
    ELSIF TG_TABLE_NAME='seat_change_requests' THEN
        IF TG_OP='INSERT' THEN v_ids:=ARRAY[NEW.requested_ticket_id];
        ELSIF TG_OP='DELETE' THEN v_ids:=ARRAY[OLD.requested_ticket_id];
        ELSE v_ids:=ARRAY[OLD.requested_ticket_id,NEW.requested_ticket_id]; END IF;
    ELSE
        IF TG_OP='DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
    END IF;

    FOREACH v_id IN ARRAY v_ids LOOP
        CONTINUE WHEN v_id IS NULL;

        SELECT held_quantity,sold_quantity,change_held_quantity
        INTO v_stored
        FROM tickets
        WHERE id=v_id;
        CONTINUE WHEN NOT FOUND;

        SELECT
            COALESCE(SUM(quantity) FILTER (WHERE status='held'),0),
            COALESCE(SUM(quantity) FILTER (WHERE status='paid'),0)
        INTO v_actual_held,v_actual_sold
        FROM reservations
        WHERE ticket_id=v_id;

        SELECT COALESCE(SUM(quantity),0)
        INTO v_actual_change_held
        FROM seat_change_requests
        WHERE requested_ticket_id=v_id AND status='pending';

        IF v_stored.held_quantity<>v_actual_held
           OR v_stored.sold_quantity<>v_actual_sold
           OR v_stored.change_held_quantity<>v_actual_change_held THEN
            RAISE EXCEPTION 'Ticket % inventory mismatch. stored=(%,%,%), actual=(%,%,%).',
                v_id,
                v_stored.held_quantity,v_stored.sold_quantity,v_stored.change_held_quantity,
                v_actual_held,v_actual_sold,v_actual_change_held;
        END IF;
    END LOOP;

    IF TG_OP='DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER assert_ticket_inventory_from_tickets
AFTER INSERT OR UPDATE OR DELETE ON tickets
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION trg_assert_ticket_inventory_counters();

CREATE CONSTRAINT TRIGGER assert_ticket_inventory_from_reservations
AFTER INSERT OR UPDATE OR DELETE ON reservations
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION trg_assert_ticket_inventory_counters();

CREATE CONSTRAINT TRIGGER assert_ticket_inventory_from_seat_changes
AFTER INSERT OR UPDATE OR DELETE ON seat_change_requests
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION trg_assert_ticket_inventory_counters();

CREATE OR REPLACE FUNCTION trg_assert_reservation_financial_lifecycle()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_ids BIGINT[];
    v_id BIGINT;
    v_res RECORD;
    v_success_count BIGINT;
    v_issued_count BIGINT;
    v_canceled_issued_count BIGINT;
    v_completed_refund_count BIGINT;
BEGIN
    IF TG_TABLE_NAME='reservations' THEN
        IF TG_OP='INSERT' THEN v_ids:=ARRAY[NEW.id];
        ELSIF TG_OP='DELETE' THEN v_ids:=ARRAY[OLD.id];
        ELSE v_ids:=ARRAY[OLD.id,NEW.id]; END IF;
    ELSIF TG_TABLE_NAME='payments' THEN
        IF TG_OP='INSERT' THEN v_ids:=ARRAY[NEW.reservation_id];
        ELSIF TG_OP='DELETE' THEN v_ids:=ARRAY[OLD.reservation_id];
        ELSE v_ids:=ARRAY[OLD.reservation_id,NEW.reservation_id]; END IF;
    ELSIF TG_TABLE_NAME='issued_tickets' THEN
        IF TG_OP='INSERT' THEN v_ids:=ARRAY[NEW.reservation_id];
        ELSIF TG_OP='DELETE' THEN v_ids:=ARRAY[OLD.reservation_id];
        ELSE v_ids:=ARRAY[OLD.reservation_id,NEW.reservation_id]; END IF;
    ELSIF TG_TABLE_NAME='refunds' THEN
        IF TG_OP<>'INSERT' THEN
            SELECT p.reservation_id INTO v_id FROM payments p WHERE p.id=OLD.payment_id;
            v_ids:=ARRAY[v_id];
        ELSE
            v_ids:=ARRAY[]::BIGINT[];
        END IF;
        IF TG_OP<>'DELETE' THEN
            SELECT p.reservation_id INTO v_id FROM payments p WHERE p.id=NEW.payment_id;
            v_ids:=array_append(v_ids,v_id);
        END IF;
    ELSE
        IF TG_OP='DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
    END IF;

    FOREACH v_id IN ARRAY v_ids LOOP
        CONTINUE WHEN v_id IS NULL;

        SELECT status,quantity
        INTO v_res
        FROM reservations
        WHERE id=v_id;
        CONTINUE WHEN NOT FOUND;

        SELECT COUNT(*)
        INTO v_success_count
        FROM payments
        WHERE reservation_id=v_id AND status='successful';

        SELECT COUNT(*),COUNT(*) FILTER (WHERE status='canceled')
        INTO v_issued_count,v_canceled_issued_count
        FROM issued_tickets
        WHERE reservation_id=v_id;

        SELECT COUNT(*)
        INTO v_completed_refund_count
        FROM refunds rf
        JOIN payments p ON p.id=rf.payment_id
        WHERE p.reservation_id=v_id AND rf.status='completed';

        IF v_res.status IN ('paid','refunded') THEN
            IF v_success_count<>1 THEN
                RAISE EXCEPTION 'Reservation % in status % must have exactly one successful payment.',v_id,v_res.status;
            END IF;
            IF v_issued_count<>v_res.quantity THEN
                RAISE EXCEPTION 'Reservation % must have % issued ticket rows, found %.',v_id,v_res.quantity,v_issued_count;
            END IF;
        ELSE
            IF v_success_count<>0 OR v_issued_count<>0 OR v_completed_refund_count<>0 THEN
                RAISE EXCEPTION 'Reservation % in status % cannot have successful payment, issued ticket or completed refund rows.',v_id,v_res.status;
            END IF;
        END IF;

        IF v_res.status='paid' THEN
            IF v_completed_refund_count<>0 OR v_canceled_issued_count<>0 THEN
                RAISE EXCEPTION 'Paid reservation % cannot have a completed refund or canceled issued tickets.',v_id;
            END IF;
        ELSIF v_res.status='refunded' THEN
            IF v_completed_refund_count<>1 OR v_canceled_issued_count<>v_res.quantity THEN
                RAISE EXCEPTION 'Refunded reservation % must have one completed refund and all issued tickets canceled.',v_id;
            END IF;
        END IF;
    END LOOP;

    IF TG_OP='DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER assert_financial_lifecycle_from_reservations
AFTER INSERT OR UPDATE OR DELETE ON reservations
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION trg_assert_reservation_financial_lifecycle();

CREATE CONSTRAINT TRIGGER assert_financial_lifecycle_from_payments
AFTER INSERT OR UPDATE OR DELETE ON payments
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION trg_assert_reservation_financial_lifecycle();

CREATE CONSTRAINT TRIGGER assert_financial_lifecycle_from_issued_tickets
AFTER INSERT OR UPDATE OR DELETE ON issued_tickets
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION trg_assert_reservation_financial_lifecycle();

CREATE CONSTRAINT TRIGGER assert_financial_lifecycle_from_refunds
AFTER INSERT OR UPDATE OR DELETE ON refunds
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION trg_assert_reservation_financial_lifecycle();

CREATE OR REPLACE FUNCTION trg_assert_wallet_balance()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_ids BIGINT[];
    v_id BIGINT;
    v_balance NUMERIC(16,2);
    v_ledger NUMERIC(16,2);
BEGIN
    IF TG_TABLE_NAME='wallets' THEN
        IF TG_OP='INSERT' THEN v_ids:=ARRAY[NEW.id];
        ELSIF TG_OP='DELETE' THEN v_ids:=ARRAY[OLD.id];
        ELSE v_ids:=ARRAY[OLD.id,NEW.id]; END IF;
    ELSE
        IF TG_OP='INSERT' THEN v_ids:=ARRAY[NEW.wallet_id];
        ELSIF TG_OP='DELETE' THEN v_ids:=ARRAY[OLD.wallet_id];
        ELSE v_ids:=ARRAY[OLD.wallet_id,NEW.wallet_id]; END IF;
    END IF;

    FOREACH v_id IN ARRAY v_ids LOOP
        CONTINUE WHEN v_id IS NULL;
        SELECT balance INTO v_balance FROM wallets WHERE id=v_id;
        CONTINUE WHEN NOT FOUND;
        SELECT COALESCE(SUM(amount),0) INTO v_ledger
        FROM wallet_transactions WHERE wallet_id=v_id;
        IF v_balance<>v_ledger THEN
            RAISE EXCEPTION 'Wallet % balance % does not equal ledger total %.',v_id,v_balance,v_ledger;
        END IF;
    END LOOP;

    IF TG_OP='DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER assert_wallet_balance_from_wallets
AFTER INSERT OR UPDATE OR DELETE ON wallets
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION trg_assert_wallet_balance();

CREATE CONSTRAINT TRIGGER assert_wallet_balance_from_ledger
AFTER INSERT OR UPDATE OR DELETE ON wallet_transactions
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION trg_assert_wallet_balance();

CREATE INDEX idx_cities_province ON cities(province_id);
CREATE INDEX idx_venues_city_active ON venues(city_id) WHERE is_active;
CREATE INDEX idx_users_city ON users(city_id);
CREATE INDEX idx_users_role_active ON users(role, is_active);
CREATE INDEX idx_teams_sport_city ON teams(sport_type_id, city_id);
CREATE INDEX idx_matches_search ON matches(sport_type_id, starts_at, venue_id) WHERE is_active;
CREATE INDEX idx_matches_teams ON matches(home_team_id, away_team_id);
CREATE INDEX idx_matches_organizer ON matches(organizer_id);
CREATE INDEX idx_matches_venue_status ON matches(venue_id,status,starts_at);
CREATE INDEX idx_tickets_match_category ON tickets(match_id, ticket_category_id);
CREATE INDEX idx_tickets_available ON tickets(match_id, available_quantity, price) WHERE is_active;
CREATE INDEX idx_tickets_sale_window ON tickets(sale_starts_at,sale_ends_at) WHERE is_active;
CREATE UNIQUE INDEX uq_numbered_ticket_seat ON tickets(match_id,section_code,row_code,seat_code) WHERE is_numbered;
CREATE UNIQUE INDEX uq_general_ticket_bucket ON tickets(match_id,ticket_category_id,section_code) WHERE NOT is_numbered;
CREATE INDEX idx_ticket_amenities_amenity ON ticket_amenities(amenity_id,ticket_id);
CREATE INDEX idx_reservations_user_status ON reservations(user_id,status,reserved_at DESC);
CREATE INDEX idx_reservations_ticket_status ON reservations(ticket_id,status);
CREATE INDEX idx_reservations_canceled_by ON reservations(canceled_by,canceled_at DESC) WHERE canceled_by IS NOT NULL;
CREATE INDEX idx_reservations_expiring_holds ON reservations(expires_at) WHERE status='held';
CREATE INDEX idx_payments_reservation ON payments(reservation_id);
CREATE INDEX idx_payments_method ON payments(payment_method_id);
CREATE INDEX idx_payments_status_paid_at ON payments(status,paid_at DESC);
CREATE UNIQUE INDEX uq_payments_one_success_per_reservation ON payments(reservation_id) WHERE status='successful';
CREATE INDEX idx_wallet_transactions_wallet_time ON wallet_transactions(wallet_id,created_at DESC);
CREATE INDEX idx_wallet_transactions_payment ON wallet_transactions(payment_id) WHERE payment_id IS NOT NULL;
CREATE INDEX idx_cancellation_policies_lookup ON cancellation_policies(organizer_id,hours_before_match DESC);
CREATE INDEX idx_cancellation_requests_status ON cancellation_requests(status,requested_at);
CREATE INDEX idx_cancellation_requests_requester ON cancellation_requests(requested_by,requested_at DESC);
CREATE INDEX idx_cancellation_requests_reviewer ON cancellation_requests(reviewed_by,reviewed_at DESC) WHERE reviewed_by IS NOT NULL;
CREATE UNIQUE INDEX uq_cancellation_one_pending ON cancellation_requests(reservation_id) WHERE status='pending';
CREATE INDEX idx_refunds_wallet ON refunds(wallet_id,completed_at DESC);
CREATE INDEX idx_seat_change_requests_status ON seat_change_requests(status,requested_at);
CREATE INDEX idx_seat_change_expiring_holds ON seat_change_requests(target_hold_expires_at) WHERE status='pending';
CREATE INDEX idx_seat_change_requests_requester ON seat_change_requests(requested_by,requested_at DESC);
CREATE INDEX idx_seat_change_requests_reviewer ON seat_change_requests(reviewed_by,reviewed_at DESC) WHERE reviewed_by IS NOT NULL;
CREATE UNIQUE INDEX uq_seat_change_one_pending ON seat_change_requests(reservation_id) WHERE status='pending';
CREATE INDEX idx_issued_tickets_reservation ON issued_tickets(reservation_id);
CREATE INDEX idx_issued_tickets_status ON issued_tickets(status,issued_at DESC);
CREATE INDEX idx_reports_ticket_category ON reports(ticket_id,category_id);
CREATE INDEX idx_reports_reservation ON reports(reservation_id) WHERE reservation_id IS NOT NULL;
CREATE INDEX idx_reports_payment ON reports(payment_id) WHERE payment_id IS NOT NULL;
CREATE INDEX idx_reports_reporter ON reports(reporter_id,created_at DESC);
CREATE INDEX idx_reports_assigned_to ON reports(assigned_to,status,created_at DESC) WHERE assigned_to IS NOT NULL;
CREATE INDEX idx_reports_status_created ON reports(status,created_at DESC);
CREATE INDEX idx_history_reservation_time ON reservation_status_history(reservation_id,changed_at DESC);

CREATE INDEX idx_users_full_name_trgm
    ON users USING GIN ((lower(first_name || ' ' || last_name)) gin_trgm_ops);
CREATE INDEX idx_cities_name_trgm ON cities USING GIN (lower(name) gin_trgm_ops);
CREATE INDEX idx_sport_types_name_trgm ON sport_types USING GIN (lower(name) gin_trgm_ops);
CREATE INDEX idx_teams_name_trgm ON teams USING GIN (lower(name) gin_trgm_ops);
CREATE INDEX idx_venues_name_trgm ON venues USING GIN (lower(name) gin_trgm_ops);
CREATE INDEX idx_matches_tournament_trgm ON matches USING GIN (lower(tournament_name) gin_trgm_ops);
CREATE INDEX idx_ticket_categories_name_trgm ON ticket_categories USING GIN (lower(name) gin_trgm_ops);
CREATE INDEX idx_amenities_name_trgm ON amenities USING GIN (lower(name) gin_trgm_ops);

CREATE VIEW v_ticket_catalog AS
SELECT
    t.id AS ticket_id,
    m.id AS match_id,
    st.code AS sport_code,
    st.name AS sport_name,
    st.is_active AS sport_is_active,
    ht.name AS home_team,
    ht.is_active AS home_team_is_active,
    at.name AS away_team,
    at.is_active AS away_team_is_active,
    m.tournament_name,
    m.starts_at,
    m.ends_at,
    m.status AS match_status,
    m.is_active AS match_is_active,
    o.id AS organizer_id,
    o.name AS organizer_name,
    o.is_active AS organizer_is_active,
    v.id AS venue_id,
    v.name AS venue_name,
    v.is_active AS venue_is_active,
    c.id AS city_id,
    c.name AS city_name,
    p.name AS province_name,
    tc.code AS category_code,
    tc.name AS category_name,
    tc.is_active AS category_is_active,
    t.section_code,
    t.row_code,
    t.seat_code,
    t.is_numbered,
    t.price,
    t.total_capacity,
    t.held_quantity,
    t.sold_quantity,
    t.change_held_quantity,
    t.available_quantity,
    t.sale_starts_at,
    t.sale_ends_at,
    t.is_active,
    COALESCE(
        string_agg(DISTINCT a.name, ', ' ORDER BY a.name)
            FILTER (WHERE a.id IS NOT NULL),
        ''
    ) AS amenities
FROM tickets t
JOIN matches m ON m.id = t.match_id
JOIN sport_types st ON st.id = m.sport_type_id
JOIN teams ht ON ht.id = m.home_team_id
JOIN teams at ON at.id = m.away_team_id
JOIN organizers o ON o.id = m.organizer_id
JOIN venues v ON v.id = m.venue_id
JOIN cities c ON c.id = v.city_id
JOIN provinces p ON p.id = c.province_id
JOIN ticket_categories tc ON tc.id = t.ticket_category_id
LEFT JOIN ticket_amenities ta ON ta.ticket_id = t.id
LEFT JOIN amenities a ON a.id = ta.amenity_id
GROUP BY
    t.id, m.id, st.code, st.name, st.is_active,
    ht.name, ht.is_active, at.name, at.is_active, m.tournament_name,
    m.starts_at, m.ends_at, m.status, m.is_active,
    o.id, o.name, o.is_active,
    v.id, v.name, v.is_active, c.id, c.name, p.name,
    tc.code, tc.name, tc.is_active;

CREATE VIEW v_purchased_tickets AS
SELECT
    p.id AS payment_id,
    p.paid_at,
    p.amount AS payment_amount,
    pm.code AS payment_method,
    r.id AS reservation_id,
    r.user_id,
    u.first_name,
    u.last_name,
    u.email,
    u.phone,
    r.quantity,
    r.unit_price,
    r.total_amount,
    r.status AS reservation_status,
    t.id AS ticket_id,
    m.id AS match_id,
    st.code AS sport_code,
    st.name AS sport_name,
    ht.name AS home_team,
    at.name AS away_team,
    v.name AS venue_name,
    c.name AS venue_city,
    pr.name AS venue_province,
    tc.name AS category_name,
    t.section_code,
    t.row_code,
    t.seat_code,
    m.starts_at
FROM payments p
JOIN payment_methods pm ON pm.id = p.payment_method_id
JOIN reservations r ON r.id = p.reservation_id
JOIN users u ON u.id = r.user_id
JOIN tickets t ON t.id = r.ticket_id
JOIN matches m ON m.id = t.match_id
JOIN sport_types st ON st.id = m.sport_type_id
JOIN teams ht ON ht.id = m.home_team_id
JOIN teams at ON at.id = m.away_team_id
JOIN venues v ON v.id = m.venue_id
JOIN cities c ON c.id = v.city_id
JOIN provinces pr ON pr.id = c.province_id
JOIN ticket_categories tc ON tc.id = t.ticket_category_id
WHERE p.status = 'successful';

CREATE VIEW football_details AS
SELECT * FROM v_ticket_catalog WHERE sport_code = 'football';

CREATE VIEW volleyball_details AS
SELECT * FROM v_ticket_catalog WHERE sport_code = 'volleyball';

CREATE VIEW basketball_details AS
SELECT * FROM v_ticket_catalog WHERE sport_code = 'basketball';

COMMIT;
