BEGIN;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS session_version INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS phone_verified_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;

UPDATE users
SET email_verified_at = COALESCE(email_verified_at, created_at)
WHERE email IS NOT NULL;

UPDATE users
SET phone_verified_at = COALESCE(phone_verified_at, created_at)
WHERE phone IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_users_last_login
    ON users(last_login_at DESC NULLS LAST);

ALTER TABLE reservations
    ADD COLUMN IF NOT EXISTS support_review_status VARCHAR(30) NOT NULL DEFAULT 'not_reviewed',
    ADD COLUMN IF NOT EXISTS support_reviewed_by BIGINT,
    ADD COLUMN IF NOT EXISTS support_review_note TEXT,
    ADD COLUMN IF NOT EXISTS support_reviewed_at TIMESTAMPTZ;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'users'::regclass
          AND conname = 'chk_users_session_version'
    ) THEN
        ALTER TABLE users
            ADD CONSTRAINT chk_users_session_version CHECK (session_version > 0);
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'reservations'::regclass
          AND conname = 'chk_reservations_support_review_status'
    ) THEN
        ALTER TABLE reservations
            ADD CONSTRAINT chk_reservations_support_review_status
            CHECK (support_review_status IN ('not_reviewed','verified','needs_correction'));
    END IF;
END;
$$;

ALTER TABLE reservations
    DROP CONSTRAINT IF EXISTS fk_reservations_support_reviewer;
ALTER TABLE reservations
    ADD CONSTRAINT fk_reservations_support_reviewer
    FOREIGN KEY (support_reviewed_by) REFERENCES users(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_reservations_support_review
    ON reservations(support_review_status, support_reviewed_at DESC);

CREATE TABLE IF NOT EXISTS api_audit_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id   BIGINT,
    action          VARCHAR(100) NOT NULL,
    resource_type   VARCHAR(100) NOT NULL,
    resource_id     VARCHAR(100),
    request_id      VARCHAR(100),
    ip_address      VARCHAR(64),
    metadata        JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_api_audit_action CHECK (btrim(action) <> ''),
    CONSTRAINT chk_api_audit_resource_type CHECK (btrim(resource_type) <> '')
);

DELETE FROM api_audit_log a
WHERE a.actor_user_id IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM users u WHERE u.id = a.actor_user_id);

ALTER TABLE api_audit_log
    DROP CONSTRAINT IF EXISTS api_audit_log_actor_user_id_fkey,
    DROP CONSTRAINT IF EXISTS fk_api_audit_actor;
ALTER TABLE api_audit_log
    ADD CONSTRAINT fk_api_audit_actor
    FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_api_audit_actor_time
    ON api_audit_log(actor_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_api_audit_action_time
    ON api_audit_log(action, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_api_audit_resource
    ON api_audit_log(resource_type, resource_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_api_audit_request_id
    ON api_audit_log(request_id) WHERE request_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS search_sync_outbox (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id     BIGINT NOT NULL,
    revision      INTEGER NOT NULL DEFAULT 1,
    attempts      INTEGER NOT NULL DEFAULT 0,
    available_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_at     TIMESTAMPTZ,
    locked_by     VARCHAR(64),
    last_error    TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at  TIMESTAMPTZ,
    CONSTRAINT chk_search_outbox_ticket CHECK (ticket_id > 0),
    CONSTRAINT chk_search_outbox_revision CHECK (revision > 0),
    CONSTRAINT chk_search_outbox_attempts CHECK (attempts >= 0),
    CONSTRAINT chk_search_outbox_lock CHECK (
        (locked_at IS NULL AND locked_by IS NULL)
        OR (locked_at IS NOT NULL AND locked_by IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_search_outbox_pending_ticket
    ON search_sync_outbox(ticket_id)
    WHERE processed_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_search_outbox_available
    ON search_sync_outbox(available_at,id)
    WHERE processed_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_search_outbox_processed
    ON search_sync_outbox(processed_at)
    WHERE processed_at IS NOT NULL;

CREATE OR REPLACE FUNCTION enqueue_ticket_search_sync(p_ticket_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    IF p_ticket_id IS NULL OR p_ticket_id <= 0 THEN
        RETURN;
    END IF;
    INSERT INTO search_sync_outbox(ticket_id)
    VALUES (p_ticket_id)
    ON CONFLICT (ticket_id) WHERE processed_at IS NULL
    DO UPDATE SET
        revision=search_sync_outbox.revision+1,
        attempts=0,
        available_at=CURRENT_TIMESTAMP,
        locked_at=NULL,
        locked_by=NULL,
        last_error=NULL;
END;
$$;

CREATE OR REPLACE FUNCTION trg_search_sync_ticket()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        PERFORM enqueue_ticket_search_sync(OLD.id);
        RETURN OLD;
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.id IS DISTINCT FROM NEW.id THEN
        PERFORM enqueue_ticket_search_sync(OLD.id);
    END IF;
    PERFORM enqueue_ticket_search_sync(NEW.id);
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION trg_search_sync_ticket_amenity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        PERFORM enqueue_ticket_search_sync(OLD.ticket_id);
        RETURN OLD;
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.ticket_id IS DISTINCT FROM NEW.ticket_id THEN
        PERFORM enqueue_ticket_search_sync(OLD.ticket_id);
    END IF;
    PERFORM enqueue_ticket_search_sync(NEW.ticket_id);
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION trg_search_sync_match()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_id BIGINT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_id := OLD.id;
    ELSE
        v_id := NEW.id;
    END IF;
    PERFORM enqueue_ticket_search_sync(t.id)
    FROM tickets t WHERE t.match_id=v_id;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION trg_search_sync_team()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_id BIGINT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_id := OLD.id;
    ELSE
        v_id := NEW.id;
    END IF;
    PERFORM enqueue_ticket_search_sync(t.id)
    FROM tickets t
    JOIN matches m ON m.id=t.match_id
    WHERE m.home_team_id=v_id OR m.away_team_id=v_id;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION trg_search_sync_sport()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_id BIGINT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_id := OLD.id;
    ELSE
        v_id := NEW.id;
    END IF;
    PERFORM enqueue_ticket_search_sync(t.id)
    FROM tickets t
    JOIN matches m ON m.id=t.match_id
    WHERE m.sport_type_id=v_id;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION trg_search_sync_venue()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_id BIGINT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_id := OLD.id;
    ELSE
        v_id := NEW.id;
    END IF;
    PERFORM enqueue_ticket_search_sync(t.id)
    FROM tickets t
    JOIN matches m ON m.id=t.match_id
    WHERE m.venue_id=v_id;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION trg_search_sync_city()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_id BIGINT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_id := OLD.id;
    ELSE
        v_id := NEW.id;
    END IF;
    PERFORM enqueue_ticket_search_sync(t.id)
    FROM tickets t
    JOIN matches m ON m.id=t.match_id
    JOIN venues v ON v.id=m.venue_id
    WHERE v.city_id=v_id;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION trg_search_sync_province()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_id BIGINT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_id := OLD.id;
    ELSE
        v_id := NEW.id;
    END IF;
    PERFORM enqueue_ticket_search_sync(t.id)
    FROM tickets t
    JOIN matches m ON m.id=t.match_id
    JOIN venues v ON v.id=m.venue_id
    JOIN cities c ON c.id=v.city_id
    WHERE c.province_id=v_id;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION trg_search_sync_organizer()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_id BIGINT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_id := OLD.id;
    ELSE
        v_id := NEW.id;
    END IF;
    PERFORM enqueue_ticket_search_sync(t.id)
    FROM tickets t
    JOIN matches m ON m.id=t.match_id
    WHERE m.organizer_id=v_id;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION trg_search_sync_category()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_id BIGINT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_id := OLD.id;
    ELSE
        v_id := NEW.id;
    END IF;
    PERFORM enqueue_ticket_search_sync(t.id)
    FROM tickets t WHERE t.ticket_category_id=v_id;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION trg_search_sync_amenity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_id BIGINT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_id := OLD.id;
    ELSE
        v_id := NEW.id;
    END IF;
    PERFORM enqueue_ticket_search_sync(ta.ticket_id)
    FROM ticket_amenities ta WHERE ta.amenity_id=v_id;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS search_sync_ticket ON tickets;
CREATE TRIGGER search_sync_ticket
AFTER INSERT OR UPDATE OR DELETE ON tickets
FOR EACH ROW EXECUTE FUNCTION trg_search_sync_ticket();

DROP TRIGGER IF EXISTS search_sync_ticket_amenity ON ticket_amenities;
CREATE TRIGGER search_sync_ticket_amenity
AFTER INSERT OR UPDATE OR DELETE ON ticket_amenities
FOR EACH ROW EXECUTE FUNCTION trg_search_sync_ticket_amenity();

DROP TRIGGER IF EXISTS search_sync_match ON matches;
CREATE TRIGGER search_sync_match
AFTER INSERT OR UPDATE OR DELETE ON matches
FOR EACH ROW EXECUTE FUNCTION trg_search_sync_match();

DROP TRIGGER IF EXISTS search_sync_team ON teams;
CREATE TRIGGER search_sync_team
AFTER INSERT OR UPDATE OR DELETE ON teams
FOR EACH ROW EXECUTE FUNCTION trg_search_sync_team();

DROP TRIGGER IF EXISTS search_sync_sport ON sport_types;
CREATE TRIGGER search_sync_sport
AFTER INSERT OR UPDATE OR DELETE ON sport_types
FOR EACH ROW EXECUTE FUNCTION trg_search_sync_sport();

DROP TRIGGER IF EXISTS search_sync_venue ON venues;
CREATE TRIGGER search_sync_venue
AFTER INSERT OR UPDATE OR DELETE ON venues
FOR EACH ROW EXECUTE FUNCTION trg_search_sync_venue();

DROP TRIGGER IF EXISTS search_sync_city ON cities;
CREATE TRIGGER search_sync_city
AFTER INSERT OR UPDATE OR DELETE ON cities
FOR EACH ROW EXECUTE FUNCTION trg_search_sync_city();

DROP TRIGGER IF EXISTS search_sync_province ON provinces;
CREATE TRIGGER search_sync_province
AFTER INSERT OR UPDATE OR DELETE ON provinces
FOR EACH ROW EXECUTE FUNCTION trg_search_sync_province();

DROP TRIGGER IF EXISTS search_sync_organizer ON organizers;
CREATE TRIGGER search_sync_organizer
AFTER INSERT OR UPDATE OR DELETE ON organizers
FOR EACH ROW EXECUTE FUNCTION trg_search_sync_organizer();

DROP TRIGGER IF EXISTS search_sync_category ON ticket_categories;
CREATE TRIGGER search_sync_category
AFTER INSERT OR UPDATE OR DELETE ON ticket_categories
FOR EACH ROW EXECUTE FUNCTION trg_search_sync_category();

DROP TRIGGER IF EXISTS search_sync_amenity ON amenities;
CREATE TRIGGER search_sync_amenity
AFTER INSERT OR UPDATE OR DELETE ON amenities
FOR EACH ROW EXECUTE FUNCTION trg_search_sync_amenity();

CREATE OR REPLACE FUNCTION support_cancel_reservation(
    p_support_user_id BIGINT,
    p_reservation_id BIGINT,
    p_reason TEXT
)
RETURNS TABLE (
    reservation_id BIGINT,
    reservation_status VARCHAR,
    released_quantity INTEGER
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_reservation RECORD;
BEGIN
    IF p_support_user_id IS NULL OR p_reservation_id IS NULL THEN
        RAISE EXCEPTION 'Support user and reservation are required.';
    END IF;
    IF p_reason IS NULL OR btrim(p_reason) = '' THEN
        RAISE EXCEPTION 'Cancellation reason is required.';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM users
        WHERE id = p_support_user_id AND role = 'support' AND is_active
    ) THEN
        RAISE EXCEPTION 'User % is not an active support user.', p_support_user_id;
    END IF;

    SELECT r.id, r.status, r.ticket_id, r.quantity, r.expires_at
    INTO v_reservation
    FROM reservations r
    WHERE r.id = p_reservation_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Reservation % does not exist.', p_reservation_id;
    END IF;

    IF v_reservation.status = 'paid' THEN
        RAISE EXCEPTION 'Paid reservations must use the cancellation/refund workflow.';
    END IF;
    IF v_reservation.status <> 'held' THEN
        RAISE EXCEPTION 'Reservation status % cannot be canceled by support.', v_reservation.status;
    END IF;

    PERFORM id FROM tickets WHERE id = v_reservation.ticket_id FOR UPDATE;
    PERFORM release_pending_seat_change_holds(
        p_reservation_id,
        'Destination hold released because support canceled the reservation'
    );

    UPDATE tickets
    SET held_quantity = held_quantity - v_reservation.quantity
    WHERE id = v_reservation.ticket_id
      AND held_quantity >= v_reservation.quantity;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Ticket held counter is inconsistent for reservation %.', p_reservation_id;
    END IF;

    UPDATE reservations
    SET status = 'canceled',
        canceled_at = CURRENT_TIMESTAMP,
        canceled_by = p_support_user_id,
        cancellation_reason = btrim(p_reason)
    WHERE id = p_reservation_id;

    RETURN QUERY
    SELECT p_reservation_id, 'canceled'::VARCHAR, v_reservation.quantity;
END;
$$;


CREATE TABLE IF NOT EXISTS support_conversations (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spectator_id           BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    assigned_to            BIGINT REFERENCES users(id) ON DELETE SET NULL,
    status                 VARCHAR(20) NOT NULL DEFAULT 'open',
    subject                VARCHAR(200) NOT NULL DEFAULT 'گفتگو با پشتیبانی MahTicket',
    last_message_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    spectator_last_read_at TIMESTAMPTZ,
    support_last_read_at   TIMESTAMPTZ,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_support_conversations_spectator UNIQUE (spectator_id),
    CONSTRAINT chk_support_conversations_status CHECK (status IN ('open','closed')),
    CONSTRAINT chk_support_conversations_subject CHECK (btrim(subject) <> '')
);

CREATE TABLE IF NOT EXISTS support_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES support_conversations(id) ON DELETE CASCADE,
    sender_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    body            TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at         TIMESTAMPTZ,
    CONSTRAINT chk_support_messages_body CHECK (
        btrim(body) <> '' AND char_length(body) <= 2000
    )
);

CREATE INDEX IF NOT EXISTS idx_support_conversations_queue
    ON support_conversations(status,last_message_at DESC,id DESC);
CREATE INDEX IF NOT EXISTS idx_support_conversations_assignee
    ON support_conversations(assigned_to,status,last_message_at DESC)
    WHERE assigned_to IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_support_messages_conversation
    ON support_messages(conversation_id,id);
CREATE INDEX IF NOT EXISTS idx_support_messages_unread
    ON support_messages(conversation_id,sender_id,created_at)
    WHERE read_at IS NULL;

DROP TRIGGER IF EXISTS set_updated_at_support_conversations ON support_conversations;
CREATE TRIGGER set_updated_at_support_conversations
BEFORE UPDATE ON support_conversations
FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

CREATE OR REPLACE FUNCTION trg_validate_support_conversation_users()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM users
        WHERE id=NEW.spectator_id AND role='spectator' AND is_active
    ) THEN
        RAISE EXCEPTION 'Conversation spectator % must be an active spectator.', NEW.spectator_id;
    END IF;
    IF NEW.assigned_to IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM users
        WHERE id=NEW.assigned_to AND role='support' AND is_active
    ) THEN
        RAISE EXCEPTION 'Assigned user % must be an active support user.', NEW.assigned_to;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS validate_support_conversation_users ON support_conversations;
CREATE TRIGGER validate_support_conversation_users
BEFORE INSERT OR UPDATE OF spectator_id,assigned_to ON support_conversations
FOR EACH ROW EXECUTE FUNCTION trg_validate_support_conversation_users();

CREATE OR REPLACE FUNCTION trg_validate_support_message_sender()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_spectator_id BIGINT;
    v_role VARCHAR(20);
BEGIN
    SELECT spectator_id INTO v_spectator_id
    FROM support_conversations
    WHERE id=NEW.conversation_id;
    IF v_spectator_id IS NULL THEN
        RAISE EXCEPTION 'Support conversation % does not exist.', NEW.conversation_id;
    END IF;

    SELECT role INTO v_role FROM users WHERE id=NEW.sender_id AND is_active;
    IF v_role IS NULL THEN
        RAISE EXCEPTION 'Message sender % is not active.', NEW.sender_id;
    END IF;
    IF NEW.sender_id<>v_spectator_id AND v_role<>'support' THEN
        RAISE EXCEPTION 'Message sender must be the conversation spectator or a support user.';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS validate_support_message_sender ON support_messages;
CREATE TRIGGER validate_support_message_sender
BEFORE INSERT OR UPDATE OF conversation_id,sender_id ON support_messages
FOR EACH ROW EXECUTE FUNCTION trg_validate_support_message_sender();

COMMIT;
